name: Android CI

env:
  # The name of the main module repository
  main_project_module: Social Interaction

  # The name of the Play Store
  playstore_name: IIECat

on:
#Where release is writen , must match your branch name , I would suggest cloning your branch  at the end called release so it only builds the final code called release
  push:
    branches: [main]
  pull_request:
    branches: [main]

    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Create APK Debug
      - name: Accept Andriod SDK licenses
        run: yes | $ANDRIOD_HOME/cmdline-latest/bin/sdkmanager --licenses

         # Run Tests Builde
      - name: Run gradle tests
        run: ./gradlew test

      # Run Build Project
      - name: Build gradle project
        run: ./gradlew build

    
      
